### ISSUE TITLE
Have slight issue with Shows with No Season or Episode Numbers

### ISSUE THREAD

**Issue by atarifundotcom** [codethug/SimpleTv#21]
Currently i am downloading shows from "BUZZR" network (Gameshows). They all come in as the same title name, no Season or Episode Numbers. So they all show for example, "Card Sharks [27.3].mp4, so when i use the script it overwrites each file instead of normally windows will just create a different file name with (1) or (2) increment the same file name with a different (#) after it. 

Is there anything within that can be changed or something i can add to the command line. 

SimpleTv.Downloader.0.2.5.exe -u xxxxxx@xxxxxx -p "xxxxxxxxx" -d c:\tvshows

Other than the above with normal shows that have S00EXX in the titles, works perfectly. Also Downloading shows with S00EXX is excellent and Plex formating is so cool.  Thanks for you help.

**Comment by timlarson345** [comment]
Please run the command again with the `-l` option to enable logging.  Then attach the log to this issue and I'll take a look.

**Comment by atarifundotcom** [comment]
Ok attached the log file, not sure if i did it right. Enclosed what i could figure out. 

Command line that i used: 
SimpleTv.Downloader.0.2.5.exe -l -u x@xxxxx.xxx -p "Xxxxxxxx" -d c:\tvshows -s "Sale*"

So i have 12 episode of Sale of the Century (game show) on Simple.tv hard drive. using your program it tried to copy them to C:\TvShows but it overwrites each one. It automatically puts S00E00 on each episode. Since S00E00 exists it must automatically overwrite. I was hoping there was a parameter to not allow overwrite and just rename file with filename(1) filename (2) ect... 

On Linux ( python downloader.py ) another program from someone else. 
Is listed as: Episode Name [27.3].mp4    (episode name no S00EXX then channel it recorded from on digital tv. with a .mp4 extension). 

[SimpleTv.DownloadLog.2016-04-02_00-50-29.json.txt](https://github.com/codethug/SimpleTv/files/200604/SimpleTv.DownloadLog.2016-04-02_00-50-29.json.txt)

![image](https://cloud.githubusercontent.com/assets/18220706/14223371/2f8c2f64-f844-11e5-8308-8bb87c854c72.png)

It seems that the provider of for BUZZR doesn't give true season / Episode parameters to the guide so it just defaults to S00E00. 

Thank you again for checking this out for me. I appreciate it. I have about 452 game show episodes to copy down from my HD (44% space left) 1Tb drive.  Manually will take hours and i expect to copy cut commercials and try to put in numerical order or show order if i can from what is being broadcast. There are tens of thousands of game show episodes out there. I need a different hobby. :)    Thanks again!
- For the record, i think i am asking for a new feature as i don't think this is a problem with your code. For regular episodes of tv shows it appears to work perfectly for those. :)

**Comment by timlarson345** [comment]
Thanks for the log file - it was very helpful.

Your analysis is correct - the primary reason you are running into this is because the show does not provide season and episode numbers, and SimpleTv Downloader defaults to 0 for each.  

My first thought was that you could use the Episode name to distinguish them, by adding the `filenameformat` parameter (shorthand is `-n`), like this:
`-filenameformat "{ShowName} - {EpisodeName}.mp4"`
Unfortunately, this won't work because all of these recordings have the exact same episode name.

Your idea of having a sequence number somewhere in the filename could work.  Something like this:
`Sale of the Century - 0001.mp4`
If we took this approach, the downloader would find the largest number for `Sale of the Century - *.mp4` and add 1.

We could also add the ability to use the date/time/channel instead, like this:
`Sale of the Century - 27.3 - 2016-01-03T1630.mp4`

What do you think?  Which would work better for you?

**Comment by atarifundotcom** [comment]
Either way is great. Thank you for the fast response.

**Comment by timlarson345** [comment]
Please try the latest release.  I have added tokens that allow you to name the file using sequential numbering, date/time recorded, and channel number.

See the [NamingFormat documentation](https://github.com/codethug/SimpleTv/blob/master/doc/NamingFormat.md) for usage.

Feel free to comment further if this does not resolve the issue.
