### ISSUE TITLE
Enhancment allow to download all but  ... Show  rather than specific  

### ISSUE THREAD

**Issue by richpel** [codethug/SimpleTv#24]
Allow to exclude shows rather than include specific shows. 

Thanks

**Comment by timlarson345** [comment]
Closed by 67a4ffb4

With the 0.4 release, you will be able to exclude shows using the -x flag.  So if you want to download everything but Geraldo, you could do this:

`-x "Geraldo*"`

Also please note that the `-s` flag has been renamed to `-i` (for 'include'), in order to be consistent with the `-x` flag (exclude).
